package config

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"strings"

	lib "github.com/sebrandon1/go-skylight/lib"
)

// Generate interactively prompts the user for configuration values and writes
// a config.yaml file to the given path. If the file already exists, it opens
// it in the user's editor instead.
func Generate(path string, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return openInEditor(path)
		}
	}

	r := bufio.NewReader(os.Stdin)

	fmt.Println("skylight-bridge config generator")
	fmt.Println("================================")
	fmt.Println()

	// Authentication.
	fmt.Println("Authentication")
	fmt.Println("--------------")
	authMethod := prompt(r, "Auth method (email or token)", "email")

	var authBlock string
	var email, password, userID, token string

	if authMethod == "token" {
		userID = prompt(r, "User ID", "")
		token = prompt(r, "API Token", "")
		authBlock = fmt.Sprintf("auth:\n  user_id: %q\n  token: %q", userID, token)
	} else {
		email = prompt(r, "Email", "")
		password = prompt(r, "Password", "")
		authBlock = fmt.Sprintf("auth:\n  email: %q\n  password: %q", email, password)
	}

	// Authenticate and discover frames.
	fmt.Println()
	fmt.Println("Connecting to Skylight API...")
	frameID, err := discoverFrame(r, authMethod, email, password, userID, token)
	if err != nil {
		fmt.Printf("  Could not auto-discover frames: %v\n", err)
		fmt.Println()
		fmt.Println("Frame")
		fmt.Println("-----")
		frameID = prompt(r, "Frame ID (enter manually)", "")
	}

	fmt.Println()
	fmt.Println("Polling")
	fmt.Println("-------")
	interval := prompt(r, "Poll interval", "30s")

	fmt.Println()
	fmt.Println("Server")
	fmt.Println("------")
	addr := prompt(r, "Listen address", ":8080")

	fmt.Println()
	fmt.Println("State")
	fmt.Println("-----")
	stateFile := prompt(r, "State file path", "/data/state.json")

	fmt.Println()
	fmt.Println("Discord (optional)")
	fmt.Println("-------------------")
	discordURL := prompt(r, "Discord webhook URL (leave blank to skip)", "")

	fmt.Println()
	fmt.Println("Home Assistant (optional)")
	fmt.Println("-------------------------")
	haURL := prompt(r, "Home Assistant URL (leave blank to skip)", "")

	var haToken string
	if haURL != "" {
		haToken = prompt(r, "HA long-lived access token", "")
	}

	// Build the config file.
	var b strings.Builder
	fmt.Fprintf(&b, "# skylight-bridge configuration\n")
	fmt.Fprintf(&b, "# Generated by skylight-bridge --generate-config\n\n")
	fmt.Fprintf(&b, "%s\n\n", authBlock)
	fmt.Fprintf(&b, "frame_id: %q\n\n", frameID)
	fmt.Fprintf(&b, "polling:\n  interval: %s\n\n", interval)
	fmt.Fprintf(&b, "state_file: %q\n\n", stateFile)
	fmt.Fprintf(&b, "server:\n  addr: %q\n  event_buffer_size: 100\n\n", addr)
	fmt.Fprintf(&b, "log:\n  level: info\n  format: json\n\n")

	fmt.Fprintf(&b, "rules:\n")
	fmt.Fprintf(&b, "  # Log all chore completions.\n")
	fmt.Fprintf(&b, "  - name: log-chore-completed\n")
	fmt.Fprintf(&b, "    event: chore.completed\n")
	fmt.Fprintf(&b, "    actions:\n")
	fmt.Fprintf(&b, "      - type: log\n")
	fmt.Fprintf(&b, "        config:\n")
	fmt.Fprintf(&b, "          message: \"{{.assignee_name}} completed {{.chore_title}}\"\n\n")

	fmt.Fprintf(&b, "  # Log all reward redemptions.\n")
	fmt.Fprintf(&b, "  - name: log-reward-redeemed\n")
	fmt.Fprintf(&b, "    event: reward.redeemed\n")
	fmt.Fprintf(&b, "    actions:\n")
	fmt.Fprintf(&b, "      - type: log\n\n")

	if discordURL != "" {
		fmt.Fprintf(&b, "  # Post chore completions to Discord.\n")
		fmt.Fprintf(&b, "  - name: discord-chore-completed\n")
		fmt.Fprintf(&b, "    event: chore.completed\n")
		fmt.Fprintf(&b, "    actions:\n")
		fmt.Fprintf(&b, "      - type: discord\n")
		fmt.Fprintf(&b, "        config:\n")
		fmt.Fprintf(&b, "          webhook_url: %q\n\n", discordURL)

		fmt.Fprintf(&b, "  # Post reward redemptions to Discord.\n")
		fmt.Fprintf(&b, "  - name: discord-reward-redeemed\n")
		fmt.Fprintf(&b, "    event: reward.redeemed\n")
		fmt.Fprintf(&b, "    actions:\n")
		fmt.Fprintf(&b, "      - type: discord\n")
		fmt.Fprintf(&b, "        config:\n")
		fmt.Fprintf(&b, "          webhook_url: %q\n\n", discordURL)

		fmt.Fprintf(&b, "  # Post to Discord when a kid finishes all chores.\n")
		fmt.Fprintf(&b, "  - name: discord-all-chores-done\n")
		fmt.Fprintf(&b, "    event: chore.all_completed\n")
		fmt.Fprintf(&b, "    actions:\n")
		fmt.Fprintf(&b, "      - type: discord\n")
		fmt.Fprintf(&b, "        config:\n")
		fmt.Fprintf(&b, "          webhook_url: %q\n\n", discordURL)
	}

	if haURL != "" {
		fmt.Fprintf(&b, "  # Flash lights when a kid finishes all daily chores.\n")
		fmt.Fprintf(&b, "  # Uncomment and set entity_id to enable.\n")
		fmt.Fprintf(&b, "  # - name: all-chores-flash-lights\n")
		fmt.Fprintf(&b, "  #   event: chore.all_completed\n")
		fmt.Fprintf(&b, "  #   actions:\n")
		fmt.Fprintf(&b, "  #     - type: homeassistant\n")
		fmt.Fprintf(&b, "  #       config:\n")
		fmt.Fprintf(&b, "  #         url: %q\n", haURL)
		fmt.Fprintf(&b, "  #         token: %q\n", haToken)
		fmt.Fprintf(&b, "  #         service: light.turn_on\n")
		fmt.Fprintf(&b, "  #         entity_id: light.living_room\n")
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("writing config file: %w", err)
	}

	fmt.Println()
	fmt.Printf("Config written to %s\n", path)
	fmt.Println("Edit the file to add or modify rules, then run skylight-bridge.")
	return nil
}

func discoverFrame(r *bufio.Reader, authMethod, email, password, userID, token string) (string, error) {
	var client *lib.Client
	var err error

	if authMethod == "token" {
		client, err = lib.NewClientWithToken(userID, token)
	} else {
		client, err = lib.NewClient(email, password)
	}
	if err != nil {
		return "", err
	}

	frames, err := client.ListFrames()
	if err != nil {
		return "", err
	}

	if len(frames) == 0 {
		return "", fmt.Errorf("no frames found for this account")
	}

	if len(frames) == 1 {
		fmt.Printf("  Found frame: %s (%s)\n", frames[0].Name, frames[0].ID)
		return frames[0].ID, nil
	}

	// Multiple frames — let the user pick.
	fmt.Printf("  Found %d frames:\n", len(frames))
	for i, f := range frames {
		fmt.Printf("    %d) %s (%s)\n", i+1, f.Name, f.ID)
	}
	choice := prompt(r, fmt.Sprintf("Select frame (1-%d)", len(frames)), "1")

	var idx int
	if _, err := fmt.Sscanf(choice, "%d", &idx); err != nil || idx < 1 || idx > len(frames) {
		idx = 1
	}
	return frames[idx-1].ID, nil
}

func openInEditor(path string) error {
	editor := os.Getenv("EDITOR")
	if editor == "" {
		editor = "vi"
	}
	fmt.Printf("Config file %s already exists, opening in %s...\n", path, editor)
	cmd := exec.Command(editor, path) //nolint:gosec // $EDITOR is trusted user input
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func prompt(r *bufio.Reader, label, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("  %s [%s]: ", label, defaultVal)
	} else {
		fmt.Printf("  %s: ", label)
	}
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}
