package config

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// Generate interactively prompts the user for configuration values and writes
// a config.yaml file to the given path.
func Generate(path string) error {
	r := bufio.NewReader(os.Stdin)

	fmt.Println("skylight-bridge config generator")
	fmt.Println("================================")
	fmt.Println()

	// Authentication.
	fmt.Println("Authentication")
	fmt.Println("--------------")
	authMethod := prompt(r, "Auth method (email or token)", "email")

	var authBlock string
	if authMethod == "token" {
		userID := prompt(r, "User ID", "")
		token := prompt(r, "API Token", "")
		authBlock = fmt.Sprintf("auth:\n  user_id: %q\n  token: %q", userID, token)
	} else {
		email := prompt(r, "Email", "")
		password := prompt(r, "Password", "")
		authBlock = fmt.Sprintf("auth:\n  email: %q\n  password: %q", email, password)
	}

	fmt.Println()
	fmt.Println("Frame")
	fmt.Println("-----")
	frameID := prompt(r, "Frame ID", "")

	fmt.Println()
	fmt.Println("Polling")
	fmt.Println("-------")
	interval := prompt(r, "Poll interval", "30s")

	fmt.Println()
	fmt.Println("Server")
	fmt.Println("------")
	addr := prompt(r, "Listen address", ":8080")

	fmt.Println()
	fmt.Println("State")
	fmt.Println("-----")
	stateFile := prompt(r, "State file path", "/data/state.json")

	fmt.Println()
	fmt.Println("Home Assistant (optional)")
	fmt.Println("-------------------------")
	haURL := prompt(r, "Home Assistant URL (leave blank to skip)", "")

	var haToken string
	if haURL != "" {
		haToken = prompt(r, "HA long-lived access token", "")
	}

	// Build the config file.
	var b strings.Builder
	fmt.Fprintf(&b, "# skylight-bridge configuration\n")
	fmt.Fprintf(&b, "# Generated by skylight-bridge --generate-config\n\n")
	fmt.Fprintf(&b, "%s\n\n", authBlock)
	fmt.Fprintf(&b, "frame_id: %q\n\n", frameID)
	fmt.Fprintf(&b, "polling:\n  interval: %s\n\n", interval)
	fmt.Fprintf(&b, "state_file: %q\n\n", stateFile)
	fmt.Fprintf(&b, "server:\n  addr: %q\n  event_buffer_size: 100\n\n", addr)
	fmt.Fprintf(&b, "log:\n  level: info\n  format: json\n\n")

	fmt.Fprintf(&b, "rules:\n")
	fmt.Fprintf(&b, "  # Log all chore completions.\n")
	fmt.Fprintf(&b, "  - name: log-chore-completed\n")
	fmt.Fprintf(&b, "    event: chore.completed\n")
	fmt.Fprintf(&b, "    actions:\n")
	fmt.Fprintf(&b, "      - type: log\n")
	fmt.Fprintf(&b, "        config:\n")
	fmt.Fprintf(&b, "          message: \"{{.assignee_name}} completed {{.chore_title}}\"\n\n")

	fmt.Fprintf(&b, "  # Log all reward redemptions.\n")
	fmt.Fprintf(&b, "  - name: log-reward-redeemed\n")
	fmt.Fprintf(&b, "    event: reward.redeemed\n")
	fmt.Fprintf(&b, "    actions:\n")
	fmt.Fprintf(&b, "      - type: log\n\n")

	if haURL != "" {
		fmt.Fprintf(&b, "  # Flash lights when a kid finishes all daily chores.\n")
		fmt.Fprintf(&b, "  # Uncomment and set entity_id to enable.\n")
		fmt.Fprintf(&b, "  # - name: all-chores-flash-lights\n")
		fmt.Fprintf(&b, "  #   event: chore.all_completed\n")
		fmt.Fprintf(&b, "  #   actions:\n")
		fmt.Fprintf(&b, "  #     - type: homeassistant\n")
		fmt.Fprintf(&b, "  #       config:\n")
		fmt.Fprintf(&b, "  #         url: %q\n", haURL)
		fmt.Fprintf(&b, "  #         token: %q\n", haToken)
		fmt.Fprintf(&b, "  #         service: light.turn_on\n")
		fmt.Fprintf(&b, "  #         entity_id: light.living_room\n")
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("writing config file: %w", err)
	}

	fmt.Println()
	fmt.Printf("Config written to %s\n", path)
	fmt.Println("Edit the file to add or modify rules, then run skylight-bridge.")
	return nil
}

func prompt(r *bufio.Reader, label, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("  %s [%s]: ", label, defaultVal)
	} else {
		fmt.Printf("  %s: ", label)
	}
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}
